### PR TITLE
OpenTofu 1.6.2

### PR DESCRIPTION
**Pull request by ravager-dk**
Can be merged once chocolatey package for 1.6.1 has been approved by choco moderators

Signed-off-by: Martin Nygaard Jensen <martin@ravager.dk>

### CODE REVIEW

**Comment by ravager-dk** [comment]
Hi @chrisdecker1201 
1.6.2 is ready to merge.

Regards

**Review by chrisdecker1201 — APPROVED** [review]

**Comment by chrisdecker1201** [comment]
@ravager-dk  I think it might be useful if I migrate this repository to you. What do you think?

**Comment by ravager-dk** [comment]
I am fine with that.

**Comment by chrisdecker1201** [comment]
I'm getting the following error on GitHub: "ravager-dk/opentofu-choco already exists and You can only transfer a repository from an organization to yourself at this time"

Do you prefer another name for this repo or can you delete your fork or do you have another idea?

Additionally, I need your name on choco to set you as maintainer :)

**Comment by ravager-dk** [comment]
My user on chocolatey is "ravager".
I have deleted my fork now. I will likely migrate it into my common Choco repo in the future, but you should be able to transfer it now. ---- On Wed, 03 Apr 2024 13:17:44 +0200  ***@***.***  wrote ----
I'm getting the following error on GitHub: "ravager-dk/opentofu-choco already exists and You can only transfer a repository from an organization to yourself at this time"
Do you prefer another name for this repo or can you delete your fork or do you have another idea?
Additionally, I need your name on choco to set you as maintainer :)

**Comment by chrisdecker1201** [comment]
grafik

**Comment by chrisdecker1201** [comment]
Now I'm getting this :D "You can only transfer a repository from an organization to yourself at this time".

I think the easiest thing to do is then archive this repo and working on a fork 🤔. Sorry. I've no experience in transfering repos :)

**Comment by ravager-dk** [comment]
> Now I'm getting this :D "You can only transfer a repository from an organization to yourself at this time".
> 
> I think the easiest thing to do is then archive this repo and working on a fork 🤔. Sorry. I've no experience in transfering repos :)

Neither do I - now we know. No worries, I will merge it into my common chocolatey repo. I have yet to receive notice about accepting maintainer role in chocolatey - strange....

**Pull request merged**
