### PR TITLE
OpenTofu 1.6.1

### PR DESCRIPTION
**Pull request by ravager-dk**

### CODE REVIEW

**Review by chrisdecker1201 — APPROVED** [review]

**Comment by chrisdecker1201** [comment]
If understood the documentation correctly, I can't push this version as well as the 1.6.0 as long as there is an open moderation from chocolatey.

**Comment by ravager-dk** [comment]
That is correct. I know the automation at chocolatey had some issues recently. Perhaps a simple repush of 1.6.0 will work. ---- On man.,29 jan. 2024 07:10:25 +0100  ***@***.***  wrote ----
If understood the documentation correctly, I can't push this version as well as the 1.6.0 as long as there is an open moderation from chocolatey.

**Comment by chrisdecker1201** [comment]
Sorry :). I found the comment from the moderator. There are now .git, .gitignore files in the package which is not allowed.

I removed them now, but need now to wait until the moderator is answering.

**Comment by chrisdecker1201** [comment]
I rejecetd the 1.6.0 and now there is a "new" request for the moderator (1.6.1)

**Pull request merged**
