### PR TITLE
Fix title caps and metaname, trigger republish 1.6.0

### PR DESCRIPTION
**Pull request by ravager-dk**
Signed-off-by: Martin Nygaard Jensen <martin@ravager.dk>

### CODE REVIEW

**Review by ravager-dk — COMMENTED** [review]
Merging this will republish the 1.6.0 which should fix the dependency issue with previous publish. This issue was caused by the .portable package not yet having been approved at the time by moderators.

**Comment by ravager-dk** [comment]
@chrisdecker1201 thoughts?

**Review by chrisdecker1201 — APPROVED** [review]

**Comment by ravager-dk** [comment]
@chrisdecker1201 Hi Christian. It looks like either the workflow failed or chocolatey community went nuts. All kinds of weird files are apparently in the pushed package.

**Comment by chrisdecker1201** [comment]
@ravager-dk Are you sure.

This looks quite good for me.

~~~log
C:.
|   opentofu.portable.nuspec
|   [Content_Types].xml
|
+---package
|   \---services
|       \---metadata
|           \---core-properties
|                   3ac8455c626f4b4fae47dad103ca183d.psmdcp
|
+---tools
|       chocolateyinstall.ps1
|       LICENSE.txt
|       tofu_1.6.1_windows_386.zip
|       tofu_1.6.1_windows_amd64.zip
|       VERIFICATION.txt
|
\---_rels
        .rels
~~~

**Pull request merged**
